name: Deploy React Website to cPanel

on:
  push:
    branches:
      - main

jobs:
  deploy-react:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Node.js and npm
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Build React App for Production
        run: npm run build

      - name: Upload to cPanel (using SFTP)
        uses: <alternative_sftp_action>@<version>
        with:
          host: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          remotePath: /public_html/
          localPath: build/
          
